#!/bin/bash
# Wrapper that executes set-theme with appropriate flag according to time

HOUR=$(date +%H)
SET_THEME="$HOME/.local/bin/set-theme"
readonly HOUR SET_THEME

if [[ ! -f "$SET_THEME" ]]; then
  exit 1
fi

if [ "$HOUR" -ge 6 ] && [ "$HOUR" -lt 19 ]; then
     "$SET_THEME" -l
else
    "$SET_THEME" -d
fi
