#!/usr/bin/env bash
set -euo pipefail

NOTIFY=1

if ! command -v hyprctl > /dev/null; then
  echo "FAtAL: hyprctl not found"
fi

if command -v notify-send > /dev/null; then
  readonly NOTIFY=0
fi

if_notify(){
  local flag="$1"
  local message="$2"
  if [[ "$flag" -eq 0 ]]; then
    notify-send "$message"
  else
    echo "$message"
  fi
}

is_swap(){
  # Returns 1 when swap is off
  if ! hyprctl getoption input:kb_options | grep -q "caps:swapescape"; then
    return 1
  fi
}

swap_off(){
  hyprctl keyword input:kb_options "" > /dev/null && \
    if_notify "$NOTIFY" "Swapescape turned off"
}

swap_on(){
  hyprctl keyword input:kb_options "caps:swapescape" > /dev/null && \
    if_notify "$NOTIFY" "Swapescape turned on"
}

if is_swap; then
  swap_off
else
  swap_on 
fi
